---
# Source: helm-template/templates/locust-master-service.yaml
kind: Service
apiVersion: v1
metadata:
  name: locust-master
  namespace: default
  labels:
    app: locust-master
spec:
  ports:
    - port: 5557
      targetPort: loc-master-p1
      protocol: TCP
      name: loc-master-p1
    - port: 5558
      targetPort: loc-master-p2
      protocol: TCP
      name: loc-master-p2
  selector:
    app: locust-master
---
# Source: helm-template/templates/locust-master-service.yaml
kind: Service
apiVersion: v1
metadata:
  name: locust-master-web
  namespace: default
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: locust-master
spec:
  ports:
    - port: 8089
      targetPort: loc-master-web
      protocol: TCP
      name: loc-master-web
  selector:
    app: locust-master
  type: LoadBalancer
---
# Source: helm-template/templates/locust-master-deployment.yaml
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: locust-master
  namespace: default
  labels:
    name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
        - name: locust-master
          image: localhost:5000/loader/dna:1
          env:
            - name: LOCUST_MODE
              value: master
            - name: TARGET_HOST
              value: http://localhost:8089
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
---
# Source: helm-template/templates/locust-worker-deployment.yaml
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: locust-worker
  namespace: default
  labels:
    name: locust-worker
spec:
  replicas: 5
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: localhost:5000/loader/dna:1
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER
              value: locust-master
            - name: TARGET_HOST
              value: https://localhost:8089
